framework:
    assets:
        base_path: 'path%'
        packages:
            frontend:
                json_manifest_path: '%kernel.project_dir%/public/assets/build/manifest.json'
            backend:
                json_manifest_path: '%kernel.project_dir%/public/assets-backend/manifest.json'