framework:
  rate_limiter:
    # Поиск вопросов (не более 100 запросов за 15 минут)
    question_search:
      policy: 'fixed_window'
      limit: 100
      interval: '15 minutes'
    # Добавление ответа к вопросу (не более 100 за 10 минут)
    question_answer_add:
      policy: 'fixed_window'
      limit: 100
      interval: '10 minutes'
    # Создание вопроса
    question_add:
      policy: 'fixed_window'
      limit: 50
      interval: '10 minutes'