version: '3.7'

###########################
#     S E R V I C E S     #
###########################
services:
  ################
  #  PostgreSQL  #
  ################
  database:
    restart: always
    build:
      context: ./docker/database
      args:
        - USER_UID
        - USER_GID
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./database/data/:/var/lib/postgresql/data/
      - ./docker/database/scripts/:/docker-entrypoint-initdb.d/

  #############
  #  PHP-FPM  #
  #############
  php-fpm:
    restart: always
    build:
      context: ./docker/php-fpm
      args:
        - USER_UID
        - USER_GID
    depends_on:
      - database
    volumes:
      - ./app/:/var/www/
      - ./docker/php-fpm/99-perfomance.ini:/usr/local/etc/php/conf.d/99-perfomance.ini

  ###########
  #  NGINX  #
  ###########
  nginx:
    restart: always
    build:
      context: ./docker/nginx
      args:
        - USER_UID
        - USER_GID
    volumes:
      - ./app/:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  ###########
  #  REDIS  #
  ###########
  redis:
    restart: always
    build:
      context: ./docker/redis
      args:
        - USER_UID
        - USER_GID
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis.conf
    sysctls:
      net.core.somaxconn: '512'

  ###################
  #  ELASTICSEARCH  #
  ###################
  elasticsearch:
    restart: always
    build:
      context: ./docker/elasticsearch
      args:
        - USER_UID
        - USER_GID
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
